### PR TITLE
Fix Swift compiler warnings

### PR DESCRIPTION
**Pull request by jeanelie**
cf. https://github.com/logmatic/logmatic-ios/issues/5

### CODE REVIEW

**Comment by gpolaert** [comment]
This should be close #5

**Comment by litso** [comment]
Can you guys make a release for this please?

**Comment by gpolaert** [comment]
I will try Tomorrow

**Comment by eerie444** [comment]
Thanks for fixing this! CocoaPods has a guide to updating a pod: https://guides.cocoapods.org/making/making-a-cocoapod.html#release

**Comment by gpolaert** [comment]
Do I have to do that `pod trunk push NAME.podspec` // I'm on linux ...

**Comment by eerie444** [comment]
@gpolaert, it looks like you have to run `pod trunk push Logmatic.podspec` to push the tag you created to the CocoaPods repository.

Someone you've added as a contributor can also run the command, but it looks like that requires you to run a CocoaPods command as well. See https://guides.cocoapods.org/making/getting-setup-with-trunk#adding-other-people-as-contributors

**Comment by eerie444** [comment]
@gpolaert, by running `pod trunk info Logmatic`, I've learned that the following five accounts are currently marked as owners:

- Edouard Siegel <edouard.siegel@applidium.com>
- Antoine Kuhn <antoine.kuhn@applidium.com> 
- Nicolas Braun <nicolas.braun@applidium.com>
- Logmatic Support team <support@logmatic.io>
- Roland Borgese <roland.borgese@applidium.com>

Only these five accounts are currently authorized to push updates using `pod trunk push Logmatic.podspec`.

**Pull request merged**
